name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install unzip if not present
        run: |
          apt-get update

          if ! command -v unzip &> /dev/null; then
            echo "unzip not found, installing..."
            apt-get install -y unzip
          else
            echo "unzip is already installed"
          fi

          if ! command -v git &> /dev/null; then
            echo "git not found, installing..."
            apt-get install -y git
          else
            echo "git is already installed"
          fi
      - name: Run Claude Code
        id: claude
        uses: ogadra/claude-code-action@fix/run-action-in-collect-PATH
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Optional: Allow Claude to run specific commands
          allowed_tools: "Bash(pnpm run typecheck),Bash(pnpm run check),Bash(pnpm test)"
          
          # Optional: Add custom instructions for Claude to customize its behavior for your project
          custom_instructions: |
            必ず日本語で回答してください。フィードバックは全て日本語で行ってください。
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test
