@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/General/Mobileclient.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/NetworkingContentDelivery/CloudFront.puml

top to bottom direction

skinparam shadowing false
hide stereotype
skinparam linetype ortho
skinparam rectangle {
    BackgroundColor AWS_BG_COLOR
    BorderColor transparent
}

rectangle "$MobileclientIMG()" as users
AWSCloudGroup(cloud){
  rectangle "$CloudFrontIMG()\nCloudFront" as cloudfront #Transparent
  rectangle "$LambdaIMG()\nLambda" as lambda #Transparent
  rectangle "$DynamoDBIMG()\nDynamoDB" as dynamodb #Transparent
}

users-r->cloudfront
cloudfront-r->lambda
lambda-r->dynamodb

@enduml
